# yanked from https://github.com/PrefectHQ/prefect-collection-template/blob/main/%7B%7Bcookiecutter.collection_name%7D%7D/.github/workflows/static_analysis.yml
name: Unit tests

on: [pull_request]

jobs:
  pre-commit-checks:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit poetry
      - name: Poetry install
        run: poetry install

      - name: Run unit-tests
        run: |
          poetry run pytest tests
